name: Build and Deploy Cpp-Only
on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
env:
  IMAGE_REPOSITORY: eajkseajks
jobs:
  cpp-only:
    name: Build and deploy Cpp-Only
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cpp-only
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4.1.1
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: v2.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Log into docker.io registry
        uses: docker/login-action@v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - id: extract-metadata-runtime-base
        name: Extract docker metadata
        uses: docker/metadata-action@v5.0.0
        with:
          context: workflow
          images: |
            ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=-runtime-base-ubuntu-22.04
          tags: |
            type=schedule,pattern={{ date 'YYYYMMDD' }}
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}.{{ minor }}
            type=semver,pattern={{ major }}
            type=raw,value={{ prefix }}latest{{ suffix }},enable={{is_default_branch}}
      - id: build-and-push-runtime-base
        name: Build ${{ env.IMAGE_NAME }} container image and push to ${{ env.IMAGE_REPOSITORY }} repository
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./DevOps/Docker/Cpp-Only/Ubuntu-22.04/Runtime/Base/Dockerfile
          tags: ${{ steps.extract-metadata-runtime-base.outputs.tags }}
          labels: ${{ steps.extract-metadata-runtime-base.outputs.labels }}
          push: true
      - name: Sign ${{ env.IMAGE_NAME }} container image
        env:
          TAGS: ${{ steps.extract-metadata-runtime-base.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-runtime-base.outputs.digest }}
        run: cosign sign --yes ${TAGS}@${DIGEST}
      - id: extract-metadata-runtime-core
        name: Extract docker metadata
        uses: docker/metadata-action@v5.0.0
        with:
          context: workflow
          images: |
            ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=-runtime-core-ubuntu-22.04
          tags: |
            type=schedule,pattern={{ date 'YYYYMMDD' }}
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}.{{ minor }}
            type=semver,pattern={{ major }}
            type=raw,value={{ prefix }}latest{{ suffix }},enable={{is_default_branch}}
      - id: build-and-push-runtime-core
        name: Build ${{ env.IMAGE_NAME }} container image and push to ${{ env.IMAGE_REPOSITORY }} repository
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./DevOps/Docker/Cpp-Only/Ubuntu-22.04/Runtime/Core/Dockerfile
          build-args: |
            IMAGE_REPOSITORY=${{ env.IMAGE_REPOSITORY }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_SHA=${{ steps.build-and-push-runtime-base.outputs.digest }}
          tags: ${{ steps.extract-metadata-runtime-core.outputs.tags }}
          labels: ${{ steps.extract-metadata-runtime-core.outputs.labels }}
          push: true
      - name: Sign ${{ env.IMAGE_NAME }} container image
        env:
          TAGS: ${{ steps.extract-metadata-runtime-core.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-runtime-core.outputs.digest }}
        run: cosign sign --yes ${TAGS}@${DIGEST}
      - id: extract-metadata-sdk-core
        name: Extract docker metadata
        uses: docker/metadata-action@v5.0.0
        with:
          context: workflow
          images: |
            ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=-sdk-core-ubuntu-22.04
          tags: |
            type=schedule,pattern={{ date 'YYYYMMDD' }}
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}.{{ minor }}
            type=semver,pattern={{ major }}
            type=raw,value={{ prefix }}latest{{ suffix }},enable={{is_default_branch}}
      - id: build-and-push-sdk-core
        name: Build ${{ env.IMAGE_NAME }} container image and push to ${{ env.IMAGE_REPOSITORY }} repository
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./DevOps/Docker/Cpp-Only/Ubuntu-22.04/SDK/Core/Dockerfile
          build-args: |
            IMAGE_REPOSITORY=${{ env.IMAGE_REPOSITORY }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_SHA=${{ steps.build-and-push-runtime-core.outputs.digest }}
          tags: ${{ steps.extract-metadata-sdk-core.outputs.tags }}
          labels: ${{ steps.extract-metadata-sdk-core.outputs.labels }}
          push: true
      - name: Sign ${{ env.IMAGE_NAME }} container image
        env:
          TAGS: ${{ steps.extract-metadata-sdk-core.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-sdk-core.outputs.digest }}
        run: cosign sign --yes ${TAGS}@${DIGEST}
