#   by-EAjks.Com Development Environments
#   Copyright (C) 2022-2024 Andrea and Eric DELAGE <Contact@by-EAjks.Com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: (CI/CD) Build and deploy the cpp-only container images
on:
  push:
    branches:
      - 'main'
      - 'feature/cpp-only/**'
      - 'issue/cpp-only/**'
      - 'release/cpp-only/**'
    tags:
      - 'cpp-only-v\d+.\d+.\d+'
    paths:
      - '.github/workflows/ci-pipeline-cpp-only.yaml'
      - 'DevOps/Docker/Cpp-Only/**'
env:
  IMAGE_REPOSITORY: eajkseajks
jobs:
  build-and-push-container-image:
    name: Build and push the container image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cpp-only
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v4.2.2
        # https://github.com/actions/checkout/tags
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: v2.4.1
        # https://github.com/sigstore/cosign-installer/tags
        # https://github.com/sigstore/cosign/releases
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3.7.1
        # https://github.com/docker/setup-buildx-action/tags
      - name: Login to ${{env.IMAGE_REPOSITORY}} registry
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        # https://github.com/docker/login-action/tags
      - id: extract-metadata-runtime-base
        name: Extract the ${{env.IMAGE_NAME}}-runtime-base metadata
        uses: docker/metadata-action@v5.5.1
        with:
          context: workflow
          images: |
            ${{env.IMAGE_REPOSITORY}}/${{env.IMAGE_NAME}}-runtime-base
          flavor: |
            latest=false
            prefix=,onlatest=true
            suffix=,onlatest=true
          tags: |
            type=match,pattern=\d+.\d+.\d+
            type=match,pattern=\d+.\d+
            type=match,pattern=\d+
            type=ref,event=branch
            type=ref,prefix=pr-,event=pr
        # https://github.com/docker/metadata-action/tags
      - id: build-and-push-runtime-base
        name: Build the container image and push it to the ${{env.IMAGE_REPOSITORY}} registry
        uses: docker/build-push-action@v6.4.1
        with:
          context: .
          file: ./DevOps/Docker/Cpp-Only/Ubuntu-24.04/Runtime/Base/Dockerfile
          tags: ${{steps.extract-metadata-runtime-base.outputs.tags}}
          labels: ${{steps.extract-metadata-runtime-base.outputs.labels}}
          push: true
        # https://github.com/docker/build-push-action/tags
      - name: Sign the container image
        env:
          TAGS: ${{steps.extract-metadata-runtime-base.outputs.tags}}
          DIGEST: ${{steps.build-and-push-runtime-base.outputs.digest}}
        run: cosign sign --yes ${TAGS}@${DIGEST}
      - id: extract-metadata-runtime-core
        name: Extract docker metadata
        uses: docker/metadata-action@v5.5.1
        with:
          context: workflow
          images: |
            ${{env.IMAGE_REPOSITORY}}/${{env.IMAGE_NAME}}
          flavor: |
            latest=false
            prefix=
            suffix=-runtime-core-ubuntu-24.04
          tags: |
            type=schedule,pattern={{ date 'YYYYMMDD'}}
            type=semver,pattern={{ version}}
            type=semver,pattern={{ major}}.{{ minor}}
            type=semver,pattern={{ major}}
            type=raw,value={{ prefix}}latest{{ suffix}},enable={{is_default_branch}}
        # https://github.com/docker/metadata-action/tags
      - id: build-and-push-runtime-core
        name: Build the container image and push it to the ${{env.IMAGE_REPOSITORY}} registry
        uses: docker/build-push-action@v6.4.1
        with:
          context: .
          file: ./DevOps/Docker/Cpp-Only/Ubuntu-24.04/Runtime/Core/Dockerfile
          build-args: |
            IMAGE_REPOSITORY=${{env.IMAGE_REPOSITORY}}
            IMAGE_NAME=${{env.IMAGE_NAME}}
            IMAGE_SHA=${{steps.build-and-push-runtime-base.outputs.digest}}
          tags: ${{steps.extract-metadata-runtime-core.outputs.tags}}
          labels: ${{steps.extract-metadata-runtime-core.outputs.labels}}
          push: true
        # https://github.com/docker/build-push-action/tags
      - name: Sign the container image
        env:
          TAGS: ${{steps.extract-metadata-runtime-core.outputs.tags}}
          DIGEST: ${{steps.build-and-push-runtime-core.outputs.digest}}
        run: cosign sign --yes ${TAGS}@${DIGEST}
      - id: extract-metadata-sdk-core
        name: Extract docker metadata
        uses: docker/metadata-action@v5.5.1
        with:
          context: workflow
          images: |
            ${{env.IMAGE_REPOSITORY}}/${{env.IMAGE_NAME}}
          flavor: |
            latest=false
            prefix=
            suffix=-sdk-core-ubuntu-24.04
          tags: |
            type=schedule,pattern={{ date 'YYYYMMDD'}}
            type=semver,pattern={{ version}}
            type=semver,pattern={{ major}}.{{ minor}}
            type=semver,pattern={{ major}}
            type=raw,value={{ prefix}}latest{{ suffix}},enable={{is_default_branch}}
        # https://github.com/docker/metadata-action/tags
      - id: build-and-push-sdk-core
        name: Build the container image and push it to the ${{env.IMAGE_REPOSITORY}} registry
        uses: docker/build-push-action@v6.4.1
        with:
          context: .
          file: ./DevOps/Docker/Cpp-Only/Ubuntu-24.04/SDK/Core/Dockerfile
          build-args: |
            IMAGE_REPOSITORY=${{env.IMAGE_REPOSITORY}}
            IMAGE_NAME=${{env.IMAGE_NAME}}
            IMAGE_SHA=${{steps.build-and-push-runtime-core.outputs.digest}}
          tags: ${{steps.extract-metadata-sdk-core.outputs.tags}}
          labels: ${{steps.extract-metadata-sdk-core.outputs.labels}}
          push: true
        # https://github.com/docker/build-push-action/tags
      - name: Sign the container image
        env:
          TAGS: ${{steps.extract-metadata-sdk-core.outputs.tags}}
          DIGEST: ${{steps.build-and-push-sdk-core.outputs.digest}}
        run: cosign sign --yes ${TAGS}@${DIGEST}
